# Generated by Django 4.2 on 2023-04-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0016_agegroup_edlevel_surveyresponse_delete_corpus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgeGroup',
        ),
        migrations.DeleteModel(
            name='EdLevel',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
